# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.forward_agent = true
  config.ssh.private_key_path = ["./keys/ubuntunginx_key", "~/.vagrant.d/insecure_private_key"]

  config.vm.define "ubuntunginx" do |ubuntunginx|
    ubuntunginx.vm.box = "ubuntu/trusty64"
    ubuntunginx.vm.box_check_update = true
    ubuntunginx.vm.hostname = "ubuntunginx"
    ubuntunginx.vm.provision "file", source: "./keys/ubuntunginx_key.pub", destination: "~/.ssh/authorized_keys"
    ubuntunginx.vm.provision "shell", path: "bootstrap.sh"
    ubuntunginx.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx"
    ubuntunginx.vm.network "private_network", ip: "172.17.8.12"
    #ubuntunginx.vm.network "public_network", ip: "172.17.8.12"
    ubuntunginx.vm.synced_folder "./", "/vagrant", disabled: true
    ubuntunginx.vm.synced_folder "html", "/vagrant/html"
    ubuntunginx.vm.synced_folder "sites-enabled", "/vagrant/sites-enabled"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 1
    vb.name = "ubuntunginx"
  end

  #config.push.define "atlas" do |push|
    #push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  #end
end
