nodes = [
  { :hostname => 'admin1', :ip => '192.168.10.10', :box => 'xenial64' },
  { :hostname => 'node1',  :ip => '192.168.10.11', :box => 'xenial64', :ram => 1024, :osd => 'yes' },
  { :hostname => 'node2',  :ip => '192.168.10.12', :box => 'xenial64', :ram => 1024, :osd => 'yes' },
  { :hostname => 'node3',  :ip => '192.168.10.13', :box => 'xenial64', :ram => 1024, :osd => 'yes' },
  { :hostname => 'client1', :ip => '192.168.10.21', :box => 'xenial64' },
  { :hostname => 'client2', :ip => '192.168.10.22', :box => 'xenial64' }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |config|
      config.vm.box = "bento/ubuntu-16.04"
      config.vm.box_check_update = true
      config.vm.hostname = node[:hostname]
      config.vm.provision "shell", path: "./provisions/host-setup.sh"
      config.vm.network :private_network, ip: node[:ip], netmask: "255.255.255.0"
      config.vm.synced_folder "./", "/vagrant"

      memory = node[:ram] ? node[:ram] : 512;
      config.vm.provider :virtualbox do |vb|
        vb.name = node[:hostname]
        vb.customize [
          "modifyvm", :id,
          "--memory", memory.to_s,
        ]
        if node[:osd] == "yes"        
          vb.customize [ "createhd", "--filename", "disk_osd-#{node[:hostname]}", "--size", "10000" ]
          vb.customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 3, "--device", 0, "--type", "hdd", "--medium", "disk_osd-#{node[:hostname]}.vdi" ]
        end
      end
    end

    config.hostmanager.enabled = true
    config.hostmanager.manage_guest = true
  end
end